[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_first = "ETNsx7b2F2qDBDRrtNEFbfZBZBkZjvwWn19jN17533pT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/snow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
