[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_crud_message = "J4benTfF2csTh4GJcjrhC7zboKk8UyL8gc6B9RMGWD2H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/snow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
