[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "Cgex5vBqXkhjEhNAoRjEYuwEGwaG4tvAk1DMVsJSFRou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/snow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
